fxi

diff --git a/circle.yml b/circle.yml
--- a/circle.yml
+++ b/circle.yml
@@ -7,7 +7,18 @@ machine:
 test:
   override:
     - echo "Hello circleCI"
-    - sh install_chromedriver.sh
+    # - sh install_chromedriver.sh
+    - >
+      version=$(curl -s http://chromedriver.storage.googleapis.com/LATEST_RELEASE)
+      echo $version
+      if [[ "$version" =~ ^[0-9]+\.[0-9].*$ ]]; then
+         echo "chromedriver version is " $version
+      else
+         echo "Invalid chromedriver version!! Get latest version may be failed. Fix it." $version
+         exit 1
+      fi
+      wget https://chromedriver.storage.googleapis.com/${version}/chromedriver_linux64.zip
+      unzip chromedriver_linux64.zip
     - chromedriver -v
     # - printenv
 #    - npm install -g mocha
